name: Format code

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Run format
      run: npm run format
    - name: Check format result
      if: ${{ failure() }}
      run: |
        echo "Formatting failed. To resolve this issue, please run `npm run format` on your change."
        exit 1
    - name: Run linting
      run: npm run lint
    - name: Check lint result
      if: ${{ failure() }}
      run: |
        echo "Linting failed. To resolve this issue, please run `npm run lint-fix` on your change."
        exit 1
